---
kind: pipeline
name: dockerbuild

platform:
  os: linux
  arch: arm64

steps:
  - name: get-vault-envs
    image: docker.xps.lan/drone-amritanshu/vault-to-env
    settings:
      vault_addr: http://vault.xps.lan
      vault_token:
        from_secret: vault_token
      vault_secret_path: drone/data/ci
  - name: linting
    image: docker.xps.lan/docker-hawkins
    commands:
      - pip3 install flake8
      - flake8 .
    depends_on: [get-vault-envs]
  - name: tests
    image: docker.xps.lan/docker-hawkins
    commands:
      - pip3 install -e .[test]
      - pytest tests/
    depends_on: [get-vault-envs]
  - name: publish
    image: docker.xps.lan/docker-hawkins
    commands:
      - python3 setup.py sdist
      - pip3 install twine
      - |
          source ./vault.env && twine upload dist/* \
            --repository "${pypi_repository}" \
            --username "${pypi_username}" \
            --password "${pypi_password}"
    depends_on: [linting, tests]
    when:
      branch:
        - master
      event:
        - tag
